changelog:
  sections:
  - title: "Features 🏗️"
    labels: ["new","feature"]
  - title: "Improvements 📈"
    labels: ["enhancement","Improvement"]
  - title: "Bug Fixes 🐛"
    labels: ["fix","bug","hotfix"]
  - title: "Tasks ☑️"
    labels: ["task"]

  