# docker-compose build && docker-compose up -d
# If "docker-compose logs ckan" shows DB not ready, run "docker-compose restart ckan" a few times.

version: "3.4"

x-common-ckan-variables: &common-ckan-variables
  CKAN_SQLALCHEMY_URL: postgresql://ckan:${POSTGRES_PASSWORD}@db/ckan
  CKAN_DATASTORE_WRITE_URL: postgresql://ckan:${POSTGRES_PASSWORD}@db/datastore
  CKAN_DATASTORE_READ_URL: postgresql://datastore_ro:${DATASTORE_READONLY_PASSWORD}@db/datastore
  CKAN_SOLR_URL: http://solr:8983/solr/ckan
  CKAN_REDIS_URL: redis://redis:6379/1
  CKAN_DATAPUSHER_URL: http://datapusher:8800
  CKAN_SITE_URL: ${CKAN_SITE_URL}
  CKAN_MAX_UPLOAD_SIZE_MB: ${CKAN_MAX_UPLOAD_SIZE_MB}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  DS_RO_PASS: ${DATASTORE_READONLY_PASSWORD}
  AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  DEBUG_TB_PROFILER_ENABLED: ${DEBUG_TB_PROFILER_ENABLED}

x-ckan: &ckan_app
  container_name: ckan
  image: cioos/ckan:${CKAN_TAG}
  links:
    - db
    - solr
    - redis
  ports:
    - "0.0.0.0:${CKAN_PORT}:5000"
  environment:
    # Defaults work with linked containers, change to use own Postgres, SolR, Redis or Datapusher
    <<: *common-ckan-variables
    #- TZ=Canada/Vancouver
    # Debug with pdb (example) - Interact with `docker attach $(docker container ls -qf name=ckan)`
    #command: 'python -m pdb /usr/lib/ckan/venv/bin/ckan --config /srv/app/ckan.ini run --host 0.0.0.0 --passthrough-errors'
    #tty: true
    #stdin_open: true
  restart: unless-stopped
  volumes:
    - "/etc/localtime:/etc/localtime:ro" # remove and use TZ setting if running on windows
    - ckan_home:/srv/app
    - ckan_storage:/var/lib/ckan
    - ${CKAN_LOG_PATH}:/srv/app/logs

volumes:
  ckan_home:
  ckan_storage:
  pg_data:
  solr_data:
  redis_data:

services:
  ckan:
    <<: *ckan_app
    build:
      context: ../../
      args:
        - CKAN_SITE_URL=${CKAN_SITE_URL}
    volumes:
      - "/etc/localtime:/etc/localtime:ro" # remove and use TZ setting if running on windows
      - ckan_home:/srv/app
      - ckan_storage:/var/lib/ckan
      - ${CKAN_LOG_PATH}:/srv/app/logs
      - ./ckan-entrypoint.sh:/docker-entrypoint.d/ckan-entrypoint.sh
    depends_on:
      - db
      - solr
      - redis
    

  ckan_gather_harvester:
     <<: *ckan_app
     container_name: ckan_gather_harvester
     entrypoint: /ckan-harvester-entrypoint.sh
     user: ckan
     command: ckan --config=/srv/app/ckan.ini harvester gather-consumer
     ports: []
     volumes:
      - "/etc/localtime:/etc/localtime:ro" # remove and use TZ setting if running on windows
      - ckan_home:/srv/app
      - ckan_storage:/var/lib/ckan
      - ${CKAN_LOG_PATH}:/srv/app/logs
      - ./ckan-harvester-entrypoint.sh:/docker-entrypoint.d/ckan-harvester-entrypoint.sh
     depends_on:
       - ckan

  ckan_fetch_harvester:
     <<: *ckan_app
     container_name: ckan_fetch_harvester
     entrypoint: /ckan-harvester-entrypoint.sh
     user: ckan
     command: ckan --config=/srv/app/ckan.ini harvester fetch-consumer
     ports: []
     volumes:
      - "/etc/localtime:/etc/localtime:ro" # remove and use TZ setting if running on windows
      - ckan_home:/srv/app
      - ckan_storage:/var/lib/ckan
      - ${CKAN_LOG_PATH}:/srv/app/logs
      - ./ckan-harvester-entrypoint.sh:/docker-entrypoint.d/ckan-harvester-entrypoint.sh
     depends_on:
       - ckan
       - ckan_gather_harvester

  ckan_run_harvester:
     <<: *ckan_app
     container_name: ckan_run_harvester
     entrypoint: /ckan-run-harvester-entrypoint.sh
     user: root
     command: /bin/bash -c "echo 'ckan_run_harvester started' && cron -f 2>&1 "
     ports: []
     volumes:
      - ./ckan-run-harvester-entrypoint.sh:/docker-entrypoint.d/ckan-run-harvester-entrypoint.sh
     depends_on:
       - ckan
       - ckan_gather_harvester
       - ckan_fetch_harvester

  datapusher:
    container_name: datapusher
    image: clementmouchet/datapusher
    restart: unless-stopped
    ports:
      - "8800:8800"

  db:
    container_name: db
    image: cioos/postgresql:latest
    ports:
       - "5432:5432"
    environment:
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - "/etc/localtime:/etc/localtime:ro" # remove and use TZ setting if running on windows
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ckan"]

  solr:
    container_name: solr
    image: cioos/solr:latest
    restart: unless-stopped
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr

  # redis is used by the datapusher and the spatial fetch and gather harvesters
  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis_data:/data
