name: IYS CKAN Docker Image

on:
  workflow_dispatch:
    branches: [ iys_master ]
env:
  submod_path: "contrib/docker/src"

jobs:
  build_ckan:
    name: build IYS ckan docker image
    runs-on: ubuntu-latest
    steps:
    - if: github.event_name != 'pull_request'
      name: Checkout non pull request with submodules
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: '0'
    - run: cp ./contrib/docker/.env.template ./contrib/docker/.env
    - run: cp ./contrib/docker/production_root_url.ini ./contrib/docker/production.ini
    - run: cp ./contrib/docker/who_root_url.ini ./contrib/docker/who.ini
    - run: cp ./contrib/docker/pycsw/pycsw.cfg.template ./contrib/docker/pycsw/pycsw.cfg
    - name: Set current date as TAG env variable for push requests
      run: echo "TAG=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: satackey/action-docker-layer-caching@v0.0.8
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
    - run: docker build -t hakaiinstitute/ckan_IYS:$TAG -t hakaiinstitute/ckan:latest .
    - run: docker push hakaiinstitute/ckan:$TAG
    - run: docker push hakaiinstitute/ckan:latest
