# Trigger the workflow on milestone events
on: 
  milestone:
    types: [closed]
  workflow_dispatch:
    inputs:
      milestoneId:
        description: 'Milestone ID'     
        required: true
        default: '1'
name: Release Notes Milestone Closure
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: release_notes
    - name: get milestone ID from event
      if: ${{ github.event.milestone.id }}
      run: echo "MILESTONEID=${{ github.event.milestone.id }}" >> $GITHUB_ENV
    - name: get milestone ID from workflow
      if: ${{ github.event.inputs.milestoneId }}
      run: echo "MILESTONEID=${{ github.event.inputs.milestoneId }}" >> $GITHUB_ENV
    - name: Create Release Notes
      uses: docker://decathlon/release-notes-generator-action:3.1.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OUTPUT_FOLDER: temp_release_notes
        USE_MILESTONE_TITLE: true
        FILENAME: CIOOS_CKAN_${{ env.MILESTONEID }}
    - name: Commit release notes
      run: |
        git config user.name 'Git release notes bot'
        git config user.email 'github-actions@github.com'
        git add --all
        git commit -am "Updated release notes" && git push || echo "No changes to commit"
