name: Solr Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    name: build Solr docker image 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set current date as TAG env variable for push requests
      run: echo "TAG=$(date +'%Y-%m-%d')" >> $GITHUB_ENV    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run: docker build -t cioos/solr:$TAG -t cioos/solr:latest --file ./contrib/docker/solr/Dockerfile .
    - run: docker push cioos/solr:$TAG
    - run: docker push cioos/solr:latest
